set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE poems;
    CREATE DATABASE weather;
    GRANT ALL PRIVILEGES ON DATABASE poems TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE weather TO "$POSTGRES_USER";
EOSQL
